//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHmoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.Movimientos = new HashSet<Movimiento>();
        }
    
        public int Id { get; set; }
        public string NombreCuenta { get; set; }
        public string TipoCuenta { get; set; }
        public string Moneda { get; set; }
        public decimal BalanceInicial { get; set; }
        public int InformacionUsuarioId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual InformacionUsuario InformacionUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimientos { get; set; }
    }
}
